export $(grep -v '^#' .env | xargs -0)

git clone $GIT_SNITCHER_API $SRC_ROOT/$SRC_SNITCHER_API
git clone $GIT_SNITCHER_FRONTEND $SRC_ROOT/$SRC_SNITCHER_FRONTEND
git clone $GIT_SNITCHER_KAFKA $SRC_ROOT/$SRC_SNITCHER_KAFKA
